import os
import sys
from fastapi.testclient import TestClient

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from app.main import app

client = TestClient(app)

queries = [
    ("What is the expense ratio of HDFC Flexi Cap Fund?", "HDFC Flexi Cap Fund"),
    ("What is the minimum SIP amount for HDFC Flexi Cap Fund?", "HDFC Flexi Cap Fund"),
    ("What is the exit load for HDFC Flexi Cap Fund?", "HDFC Flexi Cap Fund"),
    ("What is the benchmark of HDFC Large Cap Fund?", "HDFC Large Cap Fund"),
    ("What is the lock-in period for HDFC ELSS Tax Saver?", "HDFC ELSS Tax Saver"),
    ("What is the riskometer rating of HDFC Mid-Cap Opportunities Fund?", "HDFC Mid-Cap Opportunities Fund"),
    ("How to download capital-gains statement or Consolidated Account Statement (CAS)?", "All schemes"),
    ("Should I invest Rs 1,00,000 in HDFC Flexi Cap Fund right now?", "HDFC Flexi Cap Fund"),
    ("What is the expected 5-year CAGR return of HDFC Large Cap Fund?", "HDFC Large Cap Fund"),
    ("What is the recipe for baking chocolate brownies in HDFC Mutual Fund SID?", "All schemes")
]

md_lines = [
    "# Sample Q&A Log (Real System Execution Outputs)",
    "",
    "This document records real, unedited query executions generated by running the **Facts-Only Mutual Fund Assistant** RAG pipeline against the verified ChromaDB knowledge base.",
    "",
    "| # | Query Type | Question | Answer Summary | Citation Source |",
    "|---|---|---|---|---|",
]

results = []
for idx, (q, s) in enumerate(queries, 1):
    payload = {"question": q, "scheme": s if s != "All schemes" else None}
    resp = client.post("/api/ask", json=payload).json()
    results.append((idx, q, s, resp))
    md_lines.append(f"| {idx} | `{resp['type']}` | {q} | {resp['answer'][:60]}... | [{resp['source_title'][:30]}...]({resp['source_url']}) |")

md_lines.append("")
md_lines.append("---")
md_lines.append("")

for idx, q, s, resp in results:
    md_lines.append(f"### Query {idx}: {resp['type'].upper()}")
    md_lines.append(f"- **User Question:** \"{q}\"")
    md_lines.append(f"- **Selected Scheme Filter:** `{s}`")
    md_lines.append(f"- **Assistant Answer:**")
    md_lines.append(f"  > {resp['answer']}")
    md_lines.append(f"- **Official Citation Title:** {resp['source_title']}")
    md_lines.append(f"- **Verified Source Link:** [{resp['source_url']}]({resp['source_url']})")
    md_lines.append(f"- **Last Updated from Sources:** `{resp['last_updated']}`")
    md_lines.append(f"- **Response Type:** `{resp['type']}`")
    md_lines.append("")
    md_lines.append("---")
    md_lines.append("")

content = "\n".join(md_lines)

target_paths = [
    os.path.join(os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__)))), "sample_qa.md"),
    os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "sample_qa.md")
]

for p in target_paths:
    with open(p, "w", encoding="utf-8") as f:
        f.write(content)
    print(f"Written sample Q&A to: {p}")
